#!/usr/bin/env python
#
_DESCRIPTION = 'Password Reset for IPA'
_LONG_DESCRIPTION = '''
Password Reset for IPA will set a random password for a user and then send them
a SMS message with their new random password.
'''
#
# - file details ----------------------------------------------------
# $Date: 2014-04-29 20:40:21 -0700 (Tue, 29 Apr 2014) $
# $Author: tprime $
# $URL: https://svn.lightcrest.com/lcsvn/systems/passwords/damnu $
_VERSION=[ '0', '0', '$Revision: 3821 $'.split(':')[1][:-1].strip() ]

# - internal configuration defaults ---------------------------------
ORG_NAME='Lightcrest'
IPA_URL='https://ipa1.sys.lightcrest.com/ipa/ui'
SMTP_HOST='localhost'
ADMIN_NAME='Bender Rodriguez'
ADMIN_EMAIL='bender@lightcrest.com'
ADMIN_SMS_LOGIN='bender@lightcrest.com'
ADMIN_SMS_PASSWORD='SECRET_GOOGLE_PASSWORD'

# - imports  --------------------------------------------------------
import sys
import ipalib
from ipalib import api
import smtplib
from email.mime.text import MIMEText
from googlevoice import Voice

api.bootstrap()
api.finalize()
api.Backend.xmlclient.connect()

user = unicode(sys.argv[1])

try:
  r = api.Command.user_show(user, all=True)
except ipalib.errors.NotFound:
  print 'User %s not found' % (user)
  sys.exit(1)

mobile = r['result']['mobile'][0]
email = r['result']['mail'][0]
fullname = r['result']['displayname'][0]

print 'Resetting password for %s' % (user)
r = api.Command['user_mod']( user, random=True )
newpass = r['result']['randompassword']

email_msg = MIMEText('''

Hi,

Your internal %s password for your account login "%s" has been reset by the administrator.

You should shortly recieve a mobile text message with the new password.

Please log into %s with this new password. You will be asked to change it immediately after you log in.

Sincerely,

  %s
  %s
''' % ( ORG_NAME, user, IPA_URL, ADMIN_NAME, ADMIN_EMAIL ) )

email_msg['Subject'] = 'Password Reset for %s' % (ORG_NAME)
email_msg['From'] = '%s <%s>' % ( ADMIN_NAME, ADMIN_EMAIL)
email_msg['To'] = '%s <%s>' % ( fullname, email )
s = smtplib.SMTP(SMTP_HOST)
s.sendmail( ADMIN_EMAIL, email, email_msg.as_string())

mobile_msg = 'Your new %s Password is "%s".' % ( ORG_NAME, newpass )

gv = Voice()
gv.login(email=ADMIN_SMS_LOGIN, passwd=ADMIN_SMS_PASSWORD)
gv.send_sms(mobile, mobile_msg)

